DesktopNotifierSync: Add `on_*` properties for class-level events
samschott/desktop-notifier pull request #207
Opened 2024-11-26 13:27 UTC by PhrozenByte

2024-11-30 21:40 UTC, samschott approved these changes

2025-04-06 12:16 UTC, samschott requested changes
Apologies for the delay in reviewing this! The change LGTM, just a minor request for change.

2025-04-06 12:16 UTC, samschott commented on src/desktop_notifier/sync.py
> +        """
Could you reference the doc strings from the `DesktopNotifier` properties here instead? This prevents us from needing to keep those texts in sync manually.

2025-04-09 12:44 UTC, PhrozenByte commented
Done. Since you haven't had other comments about #208 I've updated this PR in anticipation of #208 as well. Meaning: You must merge #208 first, then re-run CI (mypy fails until #208 is merged, but should succeed then), and then merge this PR.

2025-08-23 12:45 UTC, merged